### ISSUE TITLE
Show alert notification in the top

### ISSUE THREAD

**Issue by fizerkhan** [fabien-d/alertify.js#112]
Thanks for great library.

I want to show my alert notification in the top, not in the bottom.
Do you have configuration for that? I could not find it in the documentation.

**Comment by fabien-d** [comment]
Currently there is no setting/config for it. I'm working on making the log messages more flexible (individually control the position of each). In the meantime you can overwrite the CSS to control the position of the logs.

``` css
.alertify-logs {
    top: 10px;
    right: 10px;
}
```
