### ISSUE TITLE
plugin for use with bootstrap.

### ISSUE THREAD

**Issue by tracker1** [fabien-d/alertify.js#13]
Would be nice if this were setup as a Bootstrap.js extension, using the base theming in bootstrap as a jQuery/bootstrap extension.. the theming is likely to be pretty alien to a lot of configs out of the box, and this would at least bring it closer to something more common.. even if only as a css/less option.

**Comment by vladcosorg** [comment]
indeed, very needed!

**Comment by fabien-d** [comment]
I've split the core and theme CSS into separate files. For this one, I'm leaning towards simply adding a alertify.bootstrap.css file which would style the dialogs in a bootstrap look and feel.

**Comment by nodrog** [comment]
if you are using bootstrap with less you can use the following:

``` css

.rgba-background-color(@hex, @alpha: 1) {
  background-color: @hex;
  background-color: hsla(hue(@hex), saturation(@hex), lightness(@hex), @alpha);
}
.rgba-box-shadow(@dimentions, @hex, @alpha: 1) {
   box-shadow: @dimentions hsla(hue(@hex), saturation(@hex), lightness(@hex), @alpha);
}

.rgba-border(@details, @hex, @alpha: 1) {
  border: @details @hex;
  border: @details hsla(hue(@hex), saturation(@hex), lightness(@hex), @alpha);
}

.alertify {
  background: @white;
  border-radius: 6px;
  .rgba-border(1px solid, @black, 0.3);
  .rgba-box-shadow(0 3px 7px, @black, 0.3);
  -webkit-background-clip: padding; 
  -moz-background-clip: padding; 
  background-clip: padding-box;
}

.alertify-text {
  border: 1px solid @textColor;
  padding: 10px;
  border-radius: 4px;
}

.alertify-button {
  .btn;
  &.alertify-button-cancel {
    .btn-danger;
  }
  &.alertify-button-ok {
    .btn-success;
  }

  &:hover, &:focus {
    color:@white;
    text-decoration:none;
    outline: none;
    box-shadow: none;
  }

}

.alertify-log {
  .alert;
  &.alertify-log-error {
     .alert-error;
  }
  &.alertify-log-success {
     .alert-success;
  }
}

```

its not perfect...
