### ISSUE TITLE
"alertify.confirm" blocks mouse hover on top middle

### ISSUE THREAD

**Issue by froehr** [fabien-d/alertify.js#138]
We got a menu with css hover on our website and after using alertify.confirm its blocked till reloading the site. It seems that alertify is just in front of it (after you choose an option, too) and so the mouseover doesn't work anymore.

**Comment by fabien-d** [comment]
I'm hoping to get a fix in for this shortly.

duplicate of https://github.com/fabien-d/alertify.js/issues/137

**Comment by fabien-d** [comment]
as a quick workaround you can add the following line in `alertify.core.css` if you're using `0.3.*` or  in `alertify.css` if you're using `0.4.0rc1`.

I'd need to test that this doesn't create issues elsewhere, but it could be a hot fix in the meantime.

``` css
:root *> .alertify-hidden {
    display: block;
    visibility: hidden; /* <-- add this line */
}
```
