### ISSUE TITLE
:root *>.alertify-hidden set to display: block insted of display: none

### ISSUE THREAD

**Issue by eilders** [fabien-d/alertify.js#140]
Shouldn't

``` css
:root *>.alertify-hidden{display:block}
```

be set to:

``` css
:root *>.alertify-hidden{display:none}
```

This is causing the code to hang around and any link or navigation under it can't be clicked.

I'm using 0.3.9
