### ISSUE TITLE
Add Background Opacity effect

### ISSUE THREAD

**Issue by maximedotair** [fabien-d/alertify.js#62]
Hello, i need to create an Background Opacity effect with alertify,
but i don't have any idea. 

How we can do it ?

Thanks

**Comment by thers** [comment]
You could set the color of the back ground as rgba(255, 255, 255, .5), or
you meant image as bg?

2012/12/15 kwizfreak notifications@github.com

**Comment by fabien-d** [comment]
alertify has a transparent cover element (which prevents clicking on elements behind the dialog) that can be styled as @RiderSx mentioned.

``` css
.alertify-cover {
    // can use an image
    background: url( path_to_transparent_image );
    // or can use RGBA
    // this won't work for IE8- and would require a fallback
    background: rgba(255,255,255,.5);
}
```

**Comment by maximedotair** [comment]
i want this effect ( like an fancybox ).
Fade or opacity effect i don't know, but i see the css is : 

element.style {
    background-color: #777777;
    cursor: pointer;
    display: block;
    height: 1075px;
    opacity: 0.7;
}
#fancybox-overlay {
    display: none;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    z-index: 1100;
}

i want apply this effect on alertify if is possible.

http://d.pr/i/oXzS 

![Screenshot 2012-12-15 at 15 06 42](https://f.cloud.github.com/assets/827372/14918/d34894c8-46c0-11e2-9568-b7fda71a1bd3.png)

Thanks

**Comment by fabien-d** [comment]
you can apply the element.style to the `.alertify-cover` element.

``` css
.alertify-cover {
    background-color: #777777;
    // untested but prefix and filter must be used
    // for IE opacity support
    -moz-opacity: .7;
    -ms-filter: "alpha(opacity=70)";
    filter: alpha(opacity=70);
    opacity: .7;
}
```
